services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - wardrobemanager_mongodb:/data/db
      - wardrobemanager_mongodb_log:/var/log/mongodb
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mongodb-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-pass}
      MONGO_INITDB_DATABASE: wardrobemanagerdb

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongodb-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-pass}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER:-root}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD:-pass}

networks:
  mongodb-network:
    driver: bridge

volumes:
  wardrobemanager_mongodb:
    driver: local
  wardrobemanager_mongodb_log:
    driver: local