spring:
  application:
    name: wardrobemanager
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER:}:${MONGODB_PASSWORD}@${MONGODB_HOST}/wardrobemanagerdb