name: Tag Deploy

on:
#  pull_request:
#    branches: [ "main" ]
  push:
    tags:
      - "*"

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: stg

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker/docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"

  docker:
    runs-on: ubuntu-latest
    environment:
      name: stg
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:${{ github.ref }}